### ISSUE TITLE
Metanorma fails to include content that contains Liquid-like syntax

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#200]
Real OGC document 18-046 contains Jinja2 which is similar to Liquid syntax in the document.

```adoc
_Application Package XML/Jinja2 Template_

[source,xml]
----
...
  {% if ap.generator.uri %}<generator uri="{{ ap.generator.uri }}" version="{{ ap.generator.version }}">{{ ap.generator.title }}</generator>{% endif %}
...
              {% elif output.data_type|lower == "literaldata" %}
...
----
```

Luckily it failed on `elif`.

Trace:
```
Liquid::SyntaxError: Liquid syntax error: Unknown tag 'elif'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/block.rb:38:in `unknown_tag'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/tags/if.rb:38:in `unknown_tag'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/block.rb:68:in `block in parse_body'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:32:in `parse'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/block.rb:58:in `parse_body'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/tags/if.rb:30:in `parse'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/tag.rb:10:in `parse'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:34:in `parse'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/block.rb:58:in `parse_body'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/tags/for.rb:60:in `parse'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/tag.rb:10:in `parse'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:34:in `parse'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/block.rb:58:in `parse_body'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/tags/for.rb:60:in `parse'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/tag.rb:10:in `parse'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:34:in `parse'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/document.rb:10:in `parse'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/document.rb:5:in `parse'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/template.rb:132:in `parse'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/template.rb:116:in `parse'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/isodoc-1.0.15/lib/isodoc/function/utils.rb:133:in `liquid'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/isodoc-1.0.15/lib/isodoc/function/utils.rb:148:in `populate_template'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/isodoc-1.0.15/lib/isodoc/html_function/postprocess.rb:18:in `toHTML'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/isodoc-1.0.15/lib/isodoc/html_function/postprocess.rb:5:in `postprocess'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/isodoc-1.0.15/lib/isodoc/convert.rb:181:in `convert'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/isodoc-1.0.15/lib/isodoc/html_convert.rb:18:in `convert'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/metanorma-ogc-0.2.12/lib/metanorma/ogc/processor.rb:32:in `output'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/metanorma-0.3.18/lib/metanorma/compile.rb:192:in `block in process_extensions'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/metanorma-0.3.18/lib/metanorma/compile.rb:183:in `each'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/metanorma-0.3.18/lib/metanorma/compile.rb:183:in `process_extensions'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/metanorma-0.3.18/lib/metanorma/compile.rb:20:in `compile'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.2.8.6/lib/metanorma/cli/compiler.rb:41:in `compile_file'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.2.8.6/lib/metanorma/cli/compiler.rb:29:in `compile'
```

isodoc must not fail on such input.

This document is from https://github.com/metanorma/mn-samples-ogc/pull/12 .

**Comment by opoudjis** [comment]
While in Word the prefatory boilerplate pages, stylesheets, and header files are all parsed for Liquid before adding them to the main document, in HTML they are not; and in both cases the entire files are parsed for Liquid (in the case of Word, redundantly). That appears to have been the case from the beginning: I was careful about insulating Liquid from the body of the document in Word, but it was not important enough to do so correctly or in HTML.
