### ISSUE TITLE
Windows log.rb:35:in `initialize': No such file or directory @ rb_sysopen

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-standoc#236]
https://github.com/metanorma/mn-templates-iec/pull/2/checks?check_run_id=558012678

**Comment by CAMOBAP795** [comment]
```
C:/hostedtoolcache/windows/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.3.23/lib/asciidoctor/standoc/log.rb:35:in `initialize': No such file or directory @ rb_sysopen - result\international-standard/result\international-standard\document.err (Errno::ENOENT)
	from C:/hostedtoolcache/windows/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.3.23/lib/asciidoctor/standoc/log.rb:35:in `open'
	from C:/hostedtoolcache/windows/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.3.23/lib/asciidoctor/standoc/log.rb:35:in `write'
	from C:/hostedtoolcache/windows/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/metanorma-iso-1.3.21/lib/asciidoctor/iso/base.rb:39:in `document'
	from C:/hostedtoolcache/windows/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.3.23/lib/asciidoctor/standoc/utils.rb:116:in `convert'
	from C:/hostedtoolcache/windows/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:951:in `convert'
	from C:/hostedtoolcache/windows/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:120:in `convert'
	from C:/hostedtoolcache/windows/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/metanorma-1.0.0/lib/metanorma/input/asciidoc.rb:10:in `process'
	from C:/hostedtoolcache/windows/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/metanorma-iec-1.0.3/lib/metanorma/iec/processor.rb:25:in `input_to_isodoc'
	from C:/hostedtoolcache/windows/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/metanorma-1.0.0/lib/metanorma/compile.rb:112:in `process_input'
	from C:/hostedtoolcache/windows/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/metanorma-1.0.0/lib/metanorma/compile.rb:17:in `compile'
	from C:/hostedtoolcache/windows/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.2.10.2/lib/metanorma/cli/compiler.rb:41:in `compile_file'
	from C:/hostedtoolcache/windows/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.2.10.2/lib/metanorma/cli/compiler.rb:29:in `compile'
	from C:/hostedtoolcache/windows/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.2.10.2/lib/metanorma/cli/compiler.rb:33:in `compile'
	from C:/hostedtoolcache/windows/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.2.10.2/lib/metanorma/cli/command.rb:35:in `compile'
	from C:/hostedtoolcache/windows/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from C:/hostedtoolcache/windows/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from C:/hostedtoolcache/windows/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from C:/hostedtoolcache/windows/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from C:/hostedtoolcache/windows/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.2.10.2/lib/metanorma/cli.rb:60:in `start'
	from C:/hostedtoolcache/windows/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.2.10.2/exe/metanorma:20:in `<top (required)>'
	from C:/hostedtoolcache/windows/Ruby/2.6.5/x64/bin/metanorma:23:in `load'
	from C:/hostedtoolcache/windows/Ruby/2.6.5/x64/bin/metanorma:23:in `<main>'
```

**Comment by ronaldtse** [comment]
This path `result\international-standard/result\international-standard\document.err` is clearly wrong, please help fix it. Thanks!
