### ISSUE TITLE
(URGENT) datamodel + yaml2text serious crash with NO INFORMATION

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#292]
Any crash with datamodel and yaml2text provides ZERO information on where the crash happens, and why it happens.

Any failure MUST display the actual error, not crash and burn the whole process.

```
TypeError: asciidoctor: FAILED: sources/cc-36100.adoc: Failed to load AsciiDoc document - no implicit conversion of Symbol into String
  (erb):11:in `+'
  (erb):11:in `block in render'
  (erb):10:in `each'
  (erb):10:in `with_index'
  (erb):10:in `render'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/2.6.0/erb.rb:901:in `eval'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/2.6.0/erb.rb:901:in `result'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.4.0/lib/asciidoctor/standoc/macros_yaml2text.rb:43:in `render'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.4.0/lib/asciidoctor/standoc/macros_yaml2text.rb:145:in `parse_context_block'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.4.0/lib/asciidoctor/standoc/macros_yaml2text.rb:131:in `parse_blocks_recursively'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.4.0/lib/asciidoctor/standoc/macros_yaml2text.rb:91:in `block in processed_lines'
```

This failure occurs in https://github.com/CalConnect/csd-standard-doc . Just `make clean all`.

**Comment by ronaldtse** [comment]
I've even commented out all the `[datamodel_*]` blocks, but this crash still happens.

**Comment by ronaldtse** [comment]
Apparently commenting them by `//` doesn't work.

Just in clause 6 of that document, 3 out of 4 commands crash:

```
[[standardsdocument]]
== StandardDocument

//[xdatamodel_diagram,./models/views/Document.yml]

[datamodel_attributes_table,./models/models/BasicDocument.yml]

//[xdatamodel_attributes_table,./models/models/StandardDocument.yml]

//[xdatamodel_attributes_table,./models/models/BoilerplateType.yml]

```
