### ISSUE TITLE
(URGENT) Compilation Failure when fetching certain NIST references

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-standoc#298]
*Issue related to https://github.com/metanorma/mn-samples-nist/issues/43*
Compilation fails when trying to fetch either of these references:

````
[[appendixA]]
[appendix]
== References

[bibliography]
=== Guidelines and Interagency Reports

* [[[ref113,NIST SP 800-55 Rev. 1]]], National Institute of Standards and Technology Special Publication 800-55, Revision 1, _Performance Measurement Guide for Information Security_, July 2008.

* [[[ref122,NIST SP 800-65]]], National Institute of Standards and Technology Special Publication 800-65, _Integrating IT Security into the Capital Planning and Investment Control Process_, January 2005.

* [[[ref133,NIST SP 800-79-1]]], National Institute of Standards and Technology Special Publication 800-79-1, _Guidelines for the Accreditation of Personal Identity Verification Card Issuers_, June 2008.
````

Part of the compilation message is:

````
$ bundle exec metanorma -t nist -x html metanorma-nist/nist-test.adoc
[relaton] cache relaton/cache/itu/: version is obsolete and cache is cleared.
[relaton-nist] ("NIST SP 800-55 Rev. 1") fetching...
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-bib] WARNING: invalid relation type: supersedes
[relaton-nist] ("NIST SP 800-55 Rev. 1") found SP 800-55 Rev. 1
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/relaton-bib-1.1.0/lib/relaton_bib/contributor.rb:112:in `block in to_xml': undefined method `to_xml' for nil:NilClass (NoMethodError)
Did you mean?  to_yaml
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/nokogiri-1.10.9-x64-mingw32/lib/nokogiri/xml/builder.rb:394:in `insert'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/nokogiri-1.10.9-x64-mingw32/lib/nokogiri/xml/builder.rb:377:in `method_missing'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/relaton-bib-1.1.0/lib/relaton_bib/contributor.rb:109:in `to_xml'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/relaton-bib-1.1.0/lib/relaton_bib/person.rb:145:in `block (2 levels) in to_xml'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/relaton-bib-1.1.0/lib/relaton_bib/person.rb:145:in `each'
...
````

Sample file: 
[nist-test.zip](https://github.com/metanorma/metanorma-nist/files/4840977/nist-test.zip)

**Comment by ronaldtse** [comment]
Now tracked at https://github.com/relaton/relaton-bib/issues/26

**Comment by manuel489** [comment]
Solved in https://github.com/relaton/relaton-bib/issues/26. Closing.
