### ISSUE TITLE
Create complelety bare bones PDF XSLT stylesheet for standoc

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#486]
Only for use in tutorials on metanorma.com, make this as low maintenance as possible

**Comment by Intelligent2013** [comment]
Here is xslt module: [base.standard.zip](https://github.com/metanorma/metanorma-standoc/files/6790677/base.standard.zip)

**Comment by opoudjis** [comment]
Using, thank you

**Comment by opoudjis** [comment]
Not working:

````
[INFO] XSL-FO file preparation...
Transforming... Αυγ 17, 2021 10:35:26 ΜΜ org.apache.fop.apps.FopConfParser configure
INFO: Default page-height set to: 11.00in
Αυγ 17, 2021 10:35:26 ΜΜ org.apache.fop.apps.FopConfParser configure
INFO: Default page-width set to: 8.50in
java.lang.IllegalArgumentException: Value must not be empty
	at org.apache.xmlgraphics.xmp.XMPSchemaAdapter.addStringToArray(XMPSchemaAdapter.java:76)
	at org.apache.xmlgraphics.xmp.XMPSchemaAdapter.addStringToBag(XMPSchemaAdapter.java:151)
	at org.apache.xmlgraphics.xmp.schemas.DublinCoreAdapter.addLanguage(DublinCoreAdapter.java:230)
	at org.apache.fop.pdf.PDFMetadata.createXMPFromPDFDocument(PDFMetadata.java:162)
	at org.apache.fop.render.pdf.PDFRenderingUtil.renderXMPMetadata(PDFRenderingUtil.java:254)
	at org.apache.fop.render.pdf.PDFDocumentHandler.handleExtensionObject(PDFDocumentHandler.java:324)
	at org.apache.fop.render.intermediate.util.IFDocumentHandlerProxy.handleExtensionObject(IFDocumentHandlerProxy.java:192)
	at org.apache.fop.render.intermediate.IFRenderer.startPageSequence(IFRenderer.java:518)
	at org.apache.fop.area.RenderPagesModel.checkPreparedPages(RenderPagesModel.java:172)
	at org.apache.fop.area.RenderPagesModel.addPage(RenderPagesModel.java:146)
	at org.apache.fop.layoutmgr.AbstractPageSequenceLayoutManager.finishPage(AbstractPageSequenceLayoutManager.java:316)
	at org.apache.fop.layoutmgr.PageSequenceLayoutManager.finishPage(PageSequenceLayoutManager.java:243)
	at org.apache.fop.layoutmgr.PageSequenceLayoutManager.activateLayout(PageSequenceLayoutManager.java:147)
	at org.apache.fop.area.AreaTreeHandler.endPageSequence(AreaTreeHandler.java:267)
	at org.apache.fop.fo.DelegatingFOEventHandler.endPageSequence(DelegatingFOEventHandler.java:114)
	at org.apache.fop.accessibility.fo.FO2StructureTreeConverter.endPageSequence(FO2StructureTreeConverter.java:184)
	at org.apache.fop.fo.pagination.PageSequence.endOfNode(PageSequence.java:139)
	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.endElement(FOTreeBuilder.java:362)
	at org.apache.fop.fo.FOTreeBuilder.endElement(FOTreeBuilder.java:190)
	at org.apache.xalan.transformer.TransformerIdentityImpl.endElement(TransformerIdentityImpl.java:1102)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:610)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1784)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2969)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:113)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:507)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:867)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:796)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:142)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:485)
	at org.metanorma.fop.mn2pdf.runFOP(mn2pdf.java:311)
	at org.metanorma.fop.mn2pdf.convertmn2pdf(mn2pdf.java:244)
	at org.metanorma.fop.mn2pdf.main(mn2pdf.java:528) (RuntimeError)
  Use --trace for backtrace
````

**Comment by Intelligent2013** [comment]
@opoudjis  How can I repeat it?

**Comment by opoudjis** [comment]
bundle exec asciidoctor -b standoc -r metanorma-standsoc a.adoc

Where the Gemfile includes

gem "metanorma-standoc", git: "https://github.com/riboseinc/metanorma-standoc", branch: "feature/pdf-compile"

**Comment by Intelligent2013** [comment]
Namespace changed from `https://www.metanorma.org/ns/iso` to `https://www.metanorma.org/ns/standoc` in the xslt.
