### ISSUE TITLE
Windows issue: jing.rb:127:in `split': invalid byte sequence in UTF-8 

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-standoc#539]
`C:/tools/ruby30/lib/ruby/gems/3.0.0/gems/ruby-jing-0.0.1/lib/jing.rb:127:in `split': invalid byte sequence in UTF-8 (ArgumentError)`

We mentioned it somewhere previously didn't managed to find it, now I was able to reproduce it on my own on mn-samples-iso on MSEdge VM

**Comment by CAMOBAP** [comment]
PR is prepared https://github.com/sshaw/ruby-jing/pull/1

The gem wasn't updated for more than 8 years, let's wait some time and then think about a workaround on our end if it's not possible to merge it

**Comment by CAMOBAP** [comment]
@Intelligent2013 awesome suggestion, thanks. I need to check it, but I'm sure that this is exactly what we need.
Also to be on the same page, how do you think will this approach be better than global `JAVA_OPTS` env?


@ronaldtse I agree that we need to add this to PR.

Also, I still think that better to get an error message with `?` than no error message at all, in the case of wrong encoding
So I propose to keep `valid_encoding?`

**Comment by CAMOBAP** [comment]
Merged
