### ISSUE TITLE
Error: `undefined method `init_bib_caches' for Relaton::DbCache:Class`

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-standoc#659]
I try to solve the issue: https://github.com/metanorma/metanorma-ogc/issues/403

Source document: https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/tree/1.0.1/standard

The command `bundle exec metanorma -t ogc -x presentation document.adoc` causes the error:

```
Fatal Error: undefined method `init_bib_caches' for Relaton::DbCache:Class
Traceback (most recent call last):
        29: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bin/metanorma:23:in `<main>'
        28: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bin/metanorma:23:in `load'
        27: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.20/exe/metanorma:43:in `<top (required)>'
        26: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.20/exe/metanorma:25:in `block in <top (required)>'
        25: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.20/lib/metanorma/cli.rb:34:in `start'
        24: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
        23: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        22: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        21: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
        20: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        19: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.20/lib/metanorma/cli/command.rb:47:in `compile'
        18: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.20/lib/metanorma/cli/command.rb:47:in `each'
        17: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.20/lib/metanorma/cli/command.rb:47:in `block in compile'
        16: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.20/lib/metanorma/cli/command.rb:241:in `compile_document'
        15: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.20/lib/metanorma/cli/compiler.rb:35:in `compile'
        14: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.20/lib/metanorma/cli/compiler.rb:30:in `compile'
        13: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.20/lib/metanorma/cli/compiler.rb:45:in `compile_file'
        12: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-1.4.11/lib/metanorma/compile.rb:33:in `compile'
        11: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-1.4.11/lib/metanorma/compile.rb:42:in `process_input'
        10: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-1.4.11/lib/metanorma/compile.rb:59:in `process_input_adoc'
         9: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-1.4.11/lib/metanorma/processor.rb:21:in `input_to_isodoc'
         8: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-1.4.11/lib/metanorma/input/asciidoc.rb:18:in `process'
         7: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.17/lib/asciidoctor/convert.rb:120:in `convert'
         6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.17/lib/asciidoctor/document.rb:955:in `convert'
         5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-standoc-2.1.5/lib/metanorma/standoc/utils.rb:13:in `convert'
         4: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-standoc-2.1.5/lib/metanorma/standoc/base.rb:103:in `document'
         3: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-standoc-2.1.5/lib/metanorma/standoc/base.rb:113:in `document1'
         2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-standoc-2.1.5/lib/metanorma/standoc/base.rb:35:in `init'
         1: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-standoc-2.1.5/lib/metanorma/standoc/base.rb:98:in `init_biblio'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-standoc-2.1.5/lib/metanorma/standoc/ref_sect.rb:134:in `init_bib_caches': undefined method `init_bib_caches' for Relaton::DbCache:Class (NoMethodError)
```

**Comment by opoudjis** [comment]
That is a result of an upgrade to relaton gem. I will resolve it tomorrow with release.

**Comment by opoudjis** [comment]
Have restored to relaton ability to disable local cache, by making the local_cache argument be nil.
