### ISSUE TITLE
(URGENT) Bibliographic span causing warnings with missing type

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#701]
relaton-bib has the `BibItemLocality` class that emits a warning message if the type of the locality is not provided.

https://github.com/relaton/relaton-bib/blob/d8031f228edcabeeb3998ad3a93de3f506c14da0/lib/relaton_bib/bib_item_locality.rb#L16-L27

```ruby
    def initialize(type, reference_from, reference_to = nil)
      type_ptrn = %r{section|clause|part|paragraph|chapter|page|whole|table|
        annex|figure|note|list|example|volume|issue|time|
        locality:[a-zA-Z0-9_]+}x
      unless type&.match? type_ptrn
        puts "type #{type}, reference_from #{reference_from}, reference_to #{reference_to}"
        warn "[relaton-bib] WARNING: invalid locality type: #{type}"
        raise
      end

      @type           = type
      @reference_from = reference_from
      @reference_to   = reference_to
    end
```

(@andrew2net one big problem here is the list of types should be dynamically generated, not hardcoded in a RegEx: https://github.com/relaton/relaton-bib/issues/66)

When Metanorma Standoc passes in localities, it is mistakenly not providing the `type` of the locality.

For example when given this entry:
```adoc
* [[[miller,1]]],
span:initials[H.] span:surname[Miller].
span:title[Tobler's First Law and Spatial Analysis].
span:type[inproceedings]
In: span:in_title[Annals of the Association of American Geographers].
vol. span:volume[94],
issue. span:issue[2],
pp. span:page[284-289].
doi: span:uri.doi[10.1111/j.1467-8306.2004.09402005.x].
```

This warning will show:
```
# This is because of the "volume"
# because of type=>nil, reference_from=>94, reference_to=>nil 
[relaton-bib] WARNING: invalid locality type: 
```

**Comment by ronaldtse** [comment]
Here's the trace where I forced it to fail when there is no `type`:
```ruby
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bib-1.13.14/lib/relaton_bib/bib_item_locality.rb:23:in `initialize': unhandled exception
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bib-1.13.14/lib/relaton_bib/xml_parser.rb:614:in `new'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bib-1.13.14/lib/relaton_bib/xml_parser.rb:614:in `locality'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bib-1.13.14/lib/relaton_bib/xml_parser.rb:599:in `block in localities'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.9-arm64-darwin/lib/nokogiri/xml/node_set.rb:234:in `block in each'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.9-arm64-darwin/lib/nokogiri/xml/node_set.rb:233:in `upto'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.9-arm64-darwin/lib/nokogiri/xml/node_set.rb:233:in `each'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bib-1.13.14/lib/relaton_bib/xml_parser.rb:597:in `map'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bib-1.13.14/lib/relaton_bib/xml_parser.rb:597:in `localities'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bib-1.13.14/lib/relaton_bib/xml_parser.rb:228:in `block in fetch_extent'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.9-arm64-darwin/lib/nokogiri/xml/node_set.rb:234:in `block in each'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.9-arm64-darwin/lib/nokogiri/xml/node_set.rb:233:in `upto'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.9-arm64-darwin/lib/nokogiri/xml/node_set.rb:233:in `each'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bib-1.13.14/lib/relaton_bib/xml_parser.rb:227:in `reduce'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bib-1.13.14/lib/relaton_bib/xml_parser.rb:227:in `fetch_extent'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bib-1.13.14/lib/relaton_bib/xml_parser.rb:59:in `item_data'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bib-1.13.14/lib/relaton_bib/xml_parser.rb:18:in `from_xml'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-ieee-0.1.2/lib/isodoc/ieee/presentation_ref.rb:63:in `creatornames'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-ieee-0.1.2/lib/metanorma/ieee/cleanup_ref.rb:53:in `designator_or_name'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-ieee-0.1.2/lib/metanorma/ieee/cleanup_ref.rb:34:in `sort_biblio_key'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-ieee-0.1.2/lib/metanorma/ieee/cleanup_ref.rb:25:in `block in sort_biblio'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-ieee-0.1.2/lib/metanorma/ieee/cleanup_ref.rb:24:in `sort'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-ieee-0.1.2/lib/metanorma/ieee/cleanup_ref.rb:24:in `sort_biblio'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-standoc-2.2.7/lib/metanorma/standoc/cleanup_ref.rb:15:in `biblio_reorder1'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-standoc-2.2.7/lib/metanorma/standoc/cleanup_ref.rb:23:in `block in biblio_reorder1'
```

**Comment by andrew2net** [comment]
> Here's the trace where I forced it to fail when there is no `type`:

@ronaldtse because the type is mandatory in the grammar
https://github.com/relaton/relaton-models/blob/3b419295fcdfd5c74f5d44998f6e56ed53750af3/grammars/biblio.rnc#L238

**Comment by ronaldtse** [comment]
Thanks @andrew2net , so this is really a bug.

**Comment by opoudjis** [comment]
Yes, it is. Fixing.
