### ISSUE TITLE
Bibliography: when encoding a `span:xxx` that is not allowed, need to show the actual line/text on where the error is

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#712]
When given a line like this:

```adoc
* [[[int_data_spaces_ref_model,1]]],
span:initials[B.] span:surname[Otto],
span:initials[S.] span:surname[Steinbus],
span:initials[A.] span:surname:[Teuscher],
span:initials[S.] span:surname[Lohmann].
span:type[booklet]
span:title[Reference Architecture Model - Version 3.0].
span:publisher[International Data Spaces Association].
span:date[April, 2019].
Available at: span:uri[https://internationaldataspaces.org/wp-content/uploads/IDS-Reference-Architecture-Model-3.0-2019.pdf].
```

There is an error at `span:surname:`.

The error message is:
```
Should be given :surname or :completename
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bib-1.13.15/lib/relaton_bib/full_name.rb:35:in `initialize'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bib-1.13.15/lib/relaton_bib/xml_parser.rb:411:in `new'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bib-1.13.15/lib/relaton_bib/xml_parser.rb:411:in `get_person'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bib-1.13.15/lib/relaton_bib/xml_parser.rb:508:in `block in fetch_contributors'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.9-arm64-darwin/lib/nokogiri/xml/node_set.rb:234:in `block in each'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.9-arm64-darwin/lib/nokogiri/xml/node_set.rb:233:in `upto'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.9-arm64-darwin/lib/nokogiri/xml/node_set.rb:233:in `each'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bib-1.13.15/lib/relaton_bib/xml_parser.rb:506:in `map'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bib-1.13.15/lib/relaton_bib/xml_parser.rb:506:in `fetch_contributors'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bib-1.13.15/lib/relaton_bib/xml_parser.rb:46:in `item_data'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bib-1.13.15/lib/relaton_bib/xml_parser.rb:18:in `from_xml'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-render-0.5.2/lib/relaton/render/general/render.rb:163:in `block in sanitise_citations_input_string'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.9-arm64-darwin/lib/nokogiri/xml/node_set.rb:234:in `block in each'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.9-arm64-darwin/lib/nokogiri/xml/node_set.rb:233:in `upto'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.9-arm64-darwin/lib/nokogiri/xml/node_set.rb:233:in `each'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-render-0.5.2/lib/relaton/render/general/render.rb:162:in `each_with_object'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-render-0.5.2/lib/relaton/render/general/render.rb:162:in `sanitise_citations_input_string'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-render-0.5.2/lib/relaton/render/general/render.rb:155:in `sanitise_citations_input'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-render-0.5.2/lib/relaton/render/general/render.rb:148:in `render_all'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.3.5/lib/isodoc/presentation_function/refs.rb:25:in `references_render'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-ieee-0.1.2/lib/isodoc/ieee/presentation_ref.rb:46:in `references_render'
```

These are the two problems:
* The document generation should NOT crash, the error message is sufficient
* Right now the process does not tell me "what is not allowed" or where the error is. It should highlight that the element `span:surname:[Teuscher]` cannot be parsed.

**Comment by opoudjis** [comment]
This is already resolved in https://github.com/metanorma/metanorma-ieee/issues/173 , released on Monday. The error message is now:

````
Bibliography: Missing surname: issue with bibliographic markup in "Reference Architecture Model - Version 3.0": {:role=>"author", :entity=>"person", :"formatted-initials"=>"A."}
Missing surname: issue with bibliographic markup in "Reference Architecture Model - Version 3.0": {:role=>"author", :entity=>"person", :"formatted-initials"=>"A."}
Missing surname: issue with bibliographic markup in "Reference Architecture Model - Version 3.0": {:role=>"author", :entity=>"person", :"formatted-initials"=>"A."}
````

> The document generation should NOT crash, the error message is sufficient

Given that the document has no idea what the surname of the author is, and therefore will generate an erroneous citation, absolutely not, it must crash. If I don't crash, Relaton will crash, which is why I've preempted it to begin with.

The alternative would be to insert "**I DO NOT KNOW WHAT THE SURNAME IS**"  as a fake surname into the document output, which is counterproductive, because people will ignore it.

> Right now the process does not tell me "what is not allowed" or where the error is. It should highlight that the element span:surname:[Teuscher] cannot be parsed.

I am now telling you as much as I can. I cannot tell you jack about the element `span:surname:[Teuscher]`, because that element is gibberish as far as Asciidoctor is concerned, and is simply not parsed: it is not available in the (by then) already parsed document, and the original Asciidoctor content is not available. That's now how Asciidoctor processing works.

I am now giving you the parsed title, which I believe satisfies the need of telling you where the error is.
