### ISSUE TITLE
Rouge crashes when displaying long Ruby code

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#737]
This issue happens when including long length Ruby code:

```
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rouge-4.0.1/lib/rouge/lexers/ruby.rb:241:in `block (2 levels) in <class:Ruby>'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rouge-4.0.1/lib/rouge/regex_lexer.rb:364:in `instance_exec'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rouge-4.0.1/lib/rouge/regex_lexer.rb:364:in `block in step'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rouge-4.0.1/lib/rouge/regex_lexer.rb:346:in `each'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rouge-4.0.1/lib/rouge/regex_lexer.rb:346:in `step'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rouge-4.0.1/lib/rouge/regex_lexer.rb:349:in `block in step'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rouge-4.0.1/lib/rouge/regex_lexer.rb:346:in `each'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rouge-4.0.1/lib/rouge/regex_lexer.rb:346:in `step'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rouge-4.0.1/lib/rouge/regex_lexer.rb:327:in `stream_tokens'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rouge-4.0.1/lib/rouge/lexer.rb:480:in `continue_lex'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rouge-4.0.1/lib/rouge/lexers/escape.rb:41:in `block in stream_tokens'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rouge-4.0.1/lib/rouge/lexers/escape.rb:38:in `loop'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rouge-4.0.1/lib/rouge/lexers/escape.rb:38:in `stream_tokens'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rouge-4.0.1/lib/rouge/lexer.rb:480:in `continue_lex'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rouge-4.0.1/lib/rouge/lexer.rb:470:in `lex'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rouge-4.0.1/lib/rouge/formatters/html.rb:20:in `each'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rouge-4.0.1/lib/rouge/formatters/html.rb:20:in `stream'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rouge-4.0.1/lib/rouge/formatter.rb:74:in `format'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.4.3/lib/isodoc/presentation_function/sourcecode.rb:46:in `source_highlight'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.4.3/lib/isodoc/presentation_function/sourcecode.rb:34:in `sourcecode1'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.4.3/lib/isodoc/presentation_function/sourcecode.rb:29:in `block in sourcecode'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.10-arm64-darwin/lib/nokogiri/xml/node_set.rb:234:in `block in each'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.10-arm64-darwin/lib/nokogiri/xml/node_set.rb:233:in `upto'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.10-arm64-darwin/lib/nokogiri/xml/node_set.rb:233:in `each'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.4.3/lib/isodoc/presentation_function/sourcecode.rb:28:in `sourcecode'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-iso-2.3.3/lib/isodoc/iso/presentation_xml_convert.rb:23:in `block'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.4.3/lib/isodoc/presentation_xml_convert.rb:31:in `conversions'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.4.3/lib/isodoc/presentation_xml_convert.rb:21:in `convert1'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-iso-2.3.3/lib/isodoc/iso/presentation_xml_convert.rb:17:in `convert1'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.4.3/lib/isodoc/convert.rb:239:in `convert'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-iso-2.3.3/lib/metanorma/iso/processor.rb:67:in `output'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.5/lib/metanorma/compile.rb:158:in `process_output_unthreaded'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.5/lib/metanorma/compile.rb:144:in `process_exts1'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.5/lib/metanorma/compile.rb:118:in `process_ext'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.5/lib/metanorma/compile.rb:106:in `block in process_exts'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.5/lib/metanorma/compile.rb:105:in `each'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.5/lib/metanorma/compile.rb:105:in `process_exts'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.5/lib/metanorma/compile.rb:37:in `compile'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.6.12/lib/metanorma/cli/compiler.rb:45:in `compile_file'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.6.12/lib/metanorma/cli/compiler.rb:30:in `compile'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.6.12/lib/metanorma/cli/compiler.rb:35:in `compile'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.6.12/lib/metanorma/cli/command.rb:244:in `compile_document'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.6.12/lib/metanorma/cli/command.rb:48:in `block in compile'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.6.12/lib/metanorma/cli/command.rb:48:in `each'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.6.12/lib/metanorma/cli/command.rb:48:in `compile'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.6.12/lib/metanorma/cli.rb:34:in `start'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.6.12/exe/metanorma:25:in `block in <top (required)>'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.6.12/exe/metanorma:43:in `<top (required)>'
ruby/3.1.2/lib/ruby/gems/3.1.0/bin/metanorma:25:in `load'
ruby/3.1.2/lib/ruby/gems/3.1.0/bin/metanorma:25:in `<top (required)>'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.2.29/lib/bundler/cli/exec.rb:58:in `load'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.2.29/lib/bundler/cli/exec.rb:58:in `kernel_load'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.2.29/lib/bundler/cli/exec.rb:23:in `run'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.2.29/lib/bundler/cli.rb:478:in `exec'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.2.29/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.2.29/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.2.29/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.2.29/lib/bundler/cli.rb:31:in `dispatch'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.2.29/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.2.29/lib/bundler/cli.rb:25:in `start'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.2.29/exe/bundle:49:in `block in <top (required)>'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.2.29/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.2.29/exe/bundle:37:in `<top (required)>'
ruby/3.1.2/bin/bundle:25:in `load'
ruby/3.1.2/bin/bundle:25:in `<main>'
No such file or directory @ rb_sysopen - /Users/mulgogi/src/mn/annotated-express/data/documents/iso-smrl-style-validation.presentation.xml
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.4.3/lib/isodoc/xslfo_convert.rb:56:in `read'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.4.3/lib/isodoc/xslfo_convert.rb:56:in `convert'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-iso-2.3.3/lib/metanorma/iso/processor.rb:58:in `output'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.5/lib/metanorma/compile.rb:149:in `process_output_threaded'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.5/lib/metanorma/compile.rb:141:in `block in process_exts1'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.5/lib/metanorma/worker_pool.rb:11:in `block (4 levels) in initialize'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.5/lib/metanorma/worker_pool.rb:9:in `loop'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.5/lib/metanorma/worker_pool.rb:9:in `block (3 levels) in initialize'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.5/lib/metanorma/worker_pool.rb:8:in `catch'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.5/lib/metanorma/worker_pool.rb:8:in `block (2 levels) in initialize'
No such file or directory @ rb_sysopen - /Users/mulgogi/src/mn/annotated-express/data/documents/iso-smrl-style-validation.presentation.xml
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.4.3/lib/isodoc/convert.rb:236:in `read'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.4.3/lib/isodoc/convert.rb:236:in `convert'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.4.3/lib/isodoc/html_convert.rb:26:in `convert'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-iso-2.3.3/lib/metanorma/iso/processor.rb:49:in `output'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.5/lib/metanorma/compile.rb:149:in `process_output_threaded'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.5/lib/metanorma/compile.rb:141:in `block in process_exts1'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.5/lib/metanorma/worker_pool.rb:11:in `block (4 levels) in initialize'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.5/lib/metanorma/worker_pool.rb:9:in `loop'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.5/lib/metanorma/worker_pool.rb:9:in `block (3 levels) in initialize'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.5/lib/metanorma/worker_pool.rb:8:in `catch'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.5/lib/metanorma/worker_pool.rb:8:in `block (2 levels) in initialize'
undefined method `<<' for nil:NilClass

          @heredoc_queue << [['<<-', '<<~'].include?(m[1]), m[3]]
                         ^^
```

I've made a PR that reproduces it:
* https://github.com/metanorma/annotated-express/pull/115

**Comment by opoudjis** [comment]
Look at the XML. The sourcecode is hopelessly corrupted, it contains raw Ruby:

````
sourcecode id="_1515c2e8-d1a2-12e7-ecce-fe28c5c8ea36" lang="ruby">{"_class"=&gt;"Expressir::Model::Declarations::Schema", "file"=&gt;"/Users/nickn/Documents/Arbeit/upwork/ribose/annotated-express/data/resources/action_schema/action_schema_annotated.exp", "id"=&gt;"action_schema", "remarks"=&gt;["The subject of the *action_schema* is the description of actions, the reasons for these actions, and the status of these actions."], "remark_items"=&gt;[{"_class"=&gt;"Expressir::Model::Declarations::RemarkItem", "id"=&gt;"__example", "remarks"=&gt;["Reasons for action include evolving user requirements, manufacturing problems and difficulties that arise when a product is in use."]}, {"_class"=&gt;"Expressir::Model::Declarations::RemarkItem", "id"=&gt;"__fund_cons", "remarks"=&gt;["Action information can be attached to any aspect of product data."]}, {"_class"=&gt;"Expressir::Model::Declarations::RemarkItem", "id"=&gt;"__expressg", "remarks"=&gt;["[.svgmap]\n====\nimage::/Users/nickn/Documents/Arbeit/upwork/ribose/annotated-express/data/resources/action_schema/action_schemaexpg1.svg[]\n\n* &lt;&lt;express:basic_attribute_schema&gt;&gt;; 1\n* &lt;&lt;express:action_schema&gt;&gt;; 2\n* &lt;&lt;express:support_resource_schema&gt;&gt;; 3\n====", "[.svgmap]\n====\nimage::/Users/nickn/Documents/Arbeit/upwork/ribose/annotated-express/data/resources/action_schema/action_schemaexpg2.svg[]\n
....
````

**Comment by opoudjis** [comment]
Need to reset the lexer between snippets, so that it can reinitialise temporary variables. (The crash here was because the queue variables for heredocs was not getting reinitialised, so it was nil.)

**Comment by ronaldtse** [comment]
> The sourcecode is hopelessly corrupted, it contains raw Ruby:

The source code is 100% correct Ruby, as we have discussed offline, and is expected to work.

NOTE that the source code being escaped is due to the debugger, not the actual text passed in.

**Comment by ronaldtse** [comment]
Thank you @opoudjis !
