### ISSUE TITLE
Failure in `embed` command when using metanorma outside of source directory

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#745]
Go to this PR:
* https://github.com/metanorma/mn-samples-bsi/pull/193

Run this command:

```sh
$ bundle exec metanorma sources/pd-iso-pas-45005/pd-iso-pas-45005.adoc 
bundler: failed to load command: metanorma (~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bin/metanorma)
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/metanorma-standoc-2ababa783520/lib/metanorma/standoc/macros_embed.rb:19:in `[]': asciidoctor: FAILED: sources/pd-iso-pas-45005/pd-iso-pas-45005.adoc: Failed to load AsciiDoc document - no implicit conversion of Symbol into Integer (TypeError)
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/metanorma-standoc-2ababa783520/lib/metanorma/standoc/macros_embed.rb:19:in `process1'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/metanorma-standoc-2ababa783520/lib/metanorma/standoc/macros_embed.rb:10:in `block in process'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/metanorma-standoc-2ababa783520/lib/metanorma/standoc/macros_embed.rb:9:in `each'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/metanorma-standoc-2ababa783520/lib/metanorma/standoc/macros_embed.rb:9:in `each_with_object'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/metanorma-standoc-2ababa783520/lib/metanorma/standoc/macros_embed.rb:9:in `process'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/asciidoctor-2.0.18/lib/asciidoctor/document.rb:533:in `[]'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/asciidoctor-2.0.18/lib/asciidoctor/document.rb:533:in `block in parse'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/asciidoctor-2.0.18/lib/asciidoctor/document.rb:532:in `each'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/asciidoctor-2.0.18/lib/asciidoctor/document.rb:532:in `parse'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/asciidoctor-2.0.18/lib/asciidoctor/load.rb:84:in `load'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.5/lib/metanorma/input/asciidoc.rb:26:in `asciidoctor_validate'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.5/lib/metanorma/input/asciidoc.rb:14:in `process'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.5/lib/metanorma/processor.rb:21:in `input_to_isodoc'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.5/lib/metanorma/compile.rb:59:in `process_input_adoc'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.5/lib/metanorma/compile.rb:42:in `process_input'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.5/lib/metanorma/compile.rb:33:in `compile'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.6.13/lib/metanorma/cli/compiler.rb:45:in `compile_file'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.6.13/lib/metanorma/cli/compiler.rb:30:in `compile'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.6.13/lib/metanorma/cli/compiler.rb:35:in `compile'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.6.13/lib/metanorma/cli/command.rb:244:in `compile_document'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.6.13/lib/metanorma/cli/command.rb:48:in `block in compile'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.6.13/lib/metanorma/cli/command.rb:48:in `each'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.6.13/lib/metanorma/cli/command.rb:48:in `compile'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.6.13/lib/metanorma/cli.rb:34:in `start'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.6.13/exe/metanorma:25:in `block in <top (required)>'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.6.13/exe/metanorma:43:in `<top (required)>'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bin/metanorma:25:in `load'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bin/metanorma:25:in `<top (required)>'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.2.25/lib/bundler/cli/exec.rb:63:in `load'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.2.25/lib/bundler/cli/exec.rb:63:in `kernel_load'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.2.25/lib/bundler/cli/exec.rb:28:in `run'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.2.25/lib/bundler/cli.rb:481:in `exec'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.2.25/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.2.25/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.2.25/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.2.25/lib/bundler/cli.rb:31:in `dispatch'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.2.25/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.2.25/lib/bundler/cli.rb:25:in `start'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.2.25/exe/bundle:49:in `block in <top (required)>'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.2.25/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.2.25/exe/bundle:37:in `<top (required)>'
	from ~/.asdf/installs/ruby/3.1.2/bin/bundle:25:in `load'
	from ~/.asdf/installs/ruby/3.1.2/bin/bundle:25:in `<main>'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/metanorma-standoc-2ababa783520/lib/metanorma/standoc/macros_embed.rb:19:in `[]': no implicit conversion of Symbol into Integer (TypeError)
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/metanorma-standoc-2ababa783520/lib/metanorma/standoc/macros_embed.rb:19:in `process1'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/metanorma-standoc-2ababa783520/lib/metanorma/standoc/macros_embed.rb:10:in `block in process'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/metanorma-standoc-2ababa783520/lib/metanorma/standoc/macros_embed.rb:9:in `each'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/metanorma-standoc-2ababa783520/lib/metanorma/standoc/macros_embed.rb:9:in `each_with_object'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/metanorma-standoc-2ababa783520/lib/metanorma/standoc/macros_embed.rb:9:in `process'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/asciidoctor-2.0.18/lib/asciidoctor/document.rb:533:in `[]'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/asciidoctor-2.0.18/lib/asciidoctor/document.rb:533:in `block in parse'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/asciidoctor-2.0.18/lib/asciidoctor/document.rb:532:in `each'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/asciidoctor-2.0.18/lib/asciidoctor/document.rb:532:in `parse'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/asciidoctor-2.0.18/lib/asciidoctor/load.rb:84:in `load'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.5/lib/metanorma/input/asciidoc.rb:26:in `asciidoctor_validate'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.5/lib/metanorma/input/asciidoc.rb:14:in `process'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.5/lib/metanorma/processor.rb:21:in `input_to_isodoc'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.5/lib/metanorma/compile.rb:59:in `process_input_adoc'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.5/lib/metanorma/compile.rb:42:in `process_input'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.5/lib/metanorma/compile.rb:33:in `compile'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.6.13/lib/metanorma/cli/compiler.rb:45:in `compile_file'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.6.13/lib/metanorma/cli/compiler.rb:30:in `compile'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.6.13/lib/metanorma/cli/compiler.rb:35:in `compile'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.6.13/lib/metanorma/cli/command.rb:244:in `compile_document'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.6.13/lib/metanorma/cli/command.rb:48:in `block in compile'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.6.13/lib/metanorma/cli/command.rb:48:in `each'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.6.13/lib/metanorma/cli/command.rb:48:in `compile'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.6.13/lib/metanorma/cli.rb:34:in `start'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.6.13/exe/metanorma:25:in `block in <top (required)>'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.6.13/exe/metanorma:43:in `<top (required)>'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bin/metanorma:25:in `load'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bin/metanorma:25:in `<top (required)>'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.2.25/lib/bundler/cli/exec.rb:63:in `load'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.2.25/lib/bundler/cli/exec.rb:63:in `kernel_load'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.2.25/lib/bundler/cli/exec.rb:28:in `run'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.2.25/lib/bundler/cli.rb:481:in `exec'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.2.25/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.2.25/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.2.25/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.2.25/lib/bundler/cli.rb:31:in `dispatch'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.2.25/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.2.25/lib/bundler/cli.rb:25:in `start'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.2.25/exe/bundle:49:in `block in <top (required)>'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.2.25/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
	from ~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.2.25/exe/bundle:37:in `<top (required)>'
	from ~/.asdf/installs/ruby/3.1.2/bin/bundle:25:in `load'
	from ~/.asdf/installs/ruby/3.1.2/bin/bundle:25:in `<main>'
```

**Comment by ronaldtse** [comment]
@CAMOBAP could you please help try fixing this issue? Thanks!

**Comment by opoudjis** [comment]
I am always angry when people are not available to relieve my workload, and this is an  ongoing failure of Ribose.

The workaround to this issue for images is to prefix their locations with the absolute path of the source document. For images, I do so in standoc rewriting paths; for includes, I do so in metanorma gem, actually rewriting the source. (It's fragile, but I was daunted by having to reengineer the implementation of includes.) I am going to extend the solution for include to embed.

**Comment by ronaldtse** [comment]
For the record @CAMOBAP was in process of evaluating this ticket. But since you know what to do this is much welcomed.
