### ISSUE TITLE
Windows-specific Ruby 3.1 `Errno::EACCES` errors

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-standoc#855]
During CI issue troubleshooting I found suspicious stacktraces that maybe potential issues. It happens only on windows and Ruby 3.1+ versions

<details>
  <summary>From `metanorma-standoc/lib/metanorma/standoc/cleanup_section.rb:199`</summary>

  ```
  <internal:kernel>:21: warning: Exception in finalizer #<Tempfile::Remover:0x000001ffe62f8270 @pid=8000, @tmpfile=#<File:D:/a/_temp/open-uri20240109-8000-qkpcnk (closed)>>
  C:/hostedtoolcache/windows/Ruby/3.2.2/x64/lib/ruby/3.2.0/tempfile.rb:279:in `unlink': Permission denied @ apply2files - D:/a/_temp/open-uri20240109-8000-qkpcnk (Errno::EACCES)
	from C:/hostedtoolcache/windows/Ruby/3.2.2/x64/lib/ruby/3.2.0/tempfile.rb:279:in `call'
	from <internal:kernel>:21:in `class'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/searchable.rb:261:in `block in extract_params'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/searchable.rb:260:in `each'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/searchable.rb:260:in `find'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/searchable.rb:260:in `extract_params'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/searchable.rb:180:in `xpath'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/searchable.rb:61:in `search'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/searchable.rb:75:in `at'
	from D:/a/metanorma-standoc/metanorma-standoc/lib/metanorma/standoc/cleanup_section.rb:199:in `sections_clausebefore_cleanup'
	from D:/a/metanorma-standoc/metanorma-standoc/lib/metanorma/standoc/cleanup_section.rb:181:in `clausebefore_cleanup'
	from D:/a/metanorma-standoc/metanorma-standoc/lib/metanorma/standoc/cleanup.rb:48:in `cleanup'
	from D:/a/metanorma-standoc/metanorma-standoc/lib/metanorma/standoc/base.rb:207:in `makexml'
	from D:/a/metanorma-standoc/metanorma-standoc/lib/metanorma/standoc/base.rb:152:in `document1'
	from D:/a/metanorma-standoc/metanorma-standoc/lib/metanorma/standoc/base.rb:141:in `document'
	from D:/a/metanorma-standoc/metanorma-standoc/lib/metanorma/standoc/utils.rb:13:in `convert'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/asciidoctor-2.0.20/lib/asciidoctor/document.rb:956:in `convert'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/asciidoctor-2.0.20/lib/asciidoctor/convert.rb:120:in `convert'
	from D:/a/metanorma-standoc/metanorma-standoc/spec/metanorma/cleanup_terms_spec.rb:1072:in `block (2 levels) in <top (required)>'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:263:in `instance_exec'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:263:in `block in run'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:511:in `block in with_around_and_singleton_context_hooks'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:468:in `block in with_around_example_hooks'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:486:in `block in run'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:626:in `block in run_around_example_hooks_for'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:352:in `call'
	from D:/a/metanorma-standoc/metanorma-standoc/spec/spec_helper.rb:40:in `block (2 levels) in <top (required)>'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:390:in `execute_with'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:352:in `call'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:629:in `run_around_example_hooks_for'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:486:in `run'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:468:in `with_around_example_hooks'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:511:in `with_around_and_singleton_context_hooks'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:259:in `run'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:646:in `block in run_examples'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:642:in `map'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:642:in `run_examples'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:607:in `run'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:121:in `map'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/configuration.rb:2070:in `with_suite_hooks'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:116:in `block in run_specs'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/reporter.rb:74:in `report'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:115:in `run_specs'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:89:in `run'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:71:in `run'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:45:in `invoke'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/exe/rspec:4:in `<main>'

  ```
</details>

<details>
  <summary>From `metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/metanorma-utils-1.7.0`</summary>

  ```
  D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/htmlentities-4.3.4/lib/htmlentities/encoder.rb:29: warning: Exception in finalizer #<Tempfile::Remover:0x000001ffea523230 @pid=8000, @tmpfile=#<File:D:/a/_temp/open-uri20240109-8000-51mqml (closed)>>
  C:/hostedtoolcache/windows/Ruby/3.2.2/x64/lib/ruby/3.2.0/tempfile.rb:279:in `unlink': Permission denied @ apply2files - D:/a/_temp/open-uri20240109-8000-51mqml (Errno::EACCES)
	from C:/hostedtoolcache/windows/Ruby/3.2.2/x64/lib/ruby/3.2.0/tempfile.rb:279:in `call'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/htmlentities-4.3.4/lib/htmlentities/encoder.rb:29:in `encoding'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/htmlentities-4.3.4/lib/htmlentities/encoder.rb:29:in `minimize_encoding'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/htmlentities-4.3.4/lib/htmlentities/encoder.rb:16:in `encode'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/htmlentities-4.3.4/lib/htmlentities.rb:73:in `encode'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/metanorma-utils-1.7.0/lib/utils/main.rb:39:in `smartformat'
	from D:/a/metanorma-standoc/metanorma-standoc/lib/metanorma/standoc/ref_queue.rb:202:in `block in smart_render_xml'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/node.rb:1235:in `traverse'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/node.rb:1234:in `block in traverse'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/node_set.rb:235:in `block in each'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/node_set.rb:234:in `upto'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/node_set.rb:234:in `each'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/node.rb:1234:in `traverse'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/node.rb:1234:in `block in traverse'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/node_set.rb:235:in `block in each'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/node_set.rb:234:in `upto'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/node_set.rb:234:in `each'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/node.rb:1234:in `traverse'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/node.rb:1234:in `block in traverse'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/node_set.rb:235:in `block in each'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/node_set.rb:234:in `upto'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/node_set.rb:234:in `each'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/node.rb:1234:in `traverse'
	from D:/a/metanorma-standoc/metanorma-standoc/lib/metanorma/standoc/ref_queue.rb:201:in `smart_render_xml'
	from D:/a/metanorma-standoc/metanorma-standoc/lib/metanorma/standoc/ref_queue.rb:208:in `use_retrieved_relaton'
	from D:/a/metanorma-standoc/metanorma-standoc/lib/metanorma/standoc/ref.rb:171:in `refitemout'
	from D:/a/metanorma-standoc/metanorma-standoc/lib/metanorma/standoc/ref.rb:224:in `reference1out'
	from D:/a/metanorma-standoc/metanorma-standoc/lib/metanorma/standoc/ref_queue.rb:27:in `block (2 levels) in references2xml'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/builder.rb:331:in `initialize'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/builder.rb:295:in `new'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/builder.rb:295:in `with'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/metanorma-utils-1.7.0/lib/utils/xml.rb:54:in `noko'
	from D:/a/metanorma-standoc/metanorma-standoc/lib/metanorma/standoc/utils.rb:21:in `noko'
	from D:/a/metanorma-standoc/metanorma-standoc/lib/metanorma/standoc/ref_queue.rb:27:in `block in references2xml'
	from D:/a/metanorma-standoc/metanorma-standoc/lib/metanorma/standoc/ref_queue.rb:26:in `map'
	from D:/a/metanorma-standoc/metanorma-standoc/lib/metanorma/standoc/ref_queue.rb:26:in `references2xml'
	from D:/a/metanorma-standoc/metanorma-standoc/lib/metanorma/standoc/ref_queue.rb:21:in `reference_populate'
	from D:/a/metanorma-standoc/metanorma-standoc/lib/metanorma/standoc/ref_queue.rb:8:in `reference'
	from D:/a/metanorma-standoc/metanorma-standoc/lib/metanorma/standoc/lists.rb:37:in `ulist'
	from D:/a/metanorma-standoc/metanorma-standoc/lib/metanorma/standoc/utils.rb:13:in `convert'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/asciidoctor-2.0.20/lib/asciidoctor/abstract_block.rb:76:in `convert'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/asciidoctor-2.0.20/lib/asciidoctor/list.rb:30:in `convert'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/asciidoctor-2.0.20/lib/asciidoctor/abstract_block.rb:85:in `block in content'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/asciidoctor-2.0.20/lib/asciidoctor/abstract_block.rb:85:in `map'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/asciidoctor-2.0.20/lib/asciidoctor/abstract_block.rb:85:in `content'
	from D:/a/metanorma-standoc/metanorma-standoc/lib/metanorma/standoc/ref_sect.rb:40:in `block in norm_ref_parse'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/builder.rb:433:in `insert'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/builder.rb:415:in `method_missing'
	from D:/a/metanorma-standoc/metanorma-standoc/lib/metanorma/standoc/ref_sect.rb:38:in `norm_ref_parse'
	from D:/a/metanorma-standoc/metanorma-standoc/lib/metanorma/standoc/section.rb:121:in `block in section'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/builder.rb:331:in `initialize'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/builder.rb:295:in `new'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/builder.rb:295:in `with'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/metanorma-utils-1.7.0/lib/utils/xml.rb:54:in `noko'
	from D:/a/metanorma-standoc/metanorma-standoc/lib/metanorma/standoc/utils.rb:21:in `noko'
	from D:/a/metanorma-standoc/metanorma-standoc/lib/metanorma/standoc/section.rb:114:in `section'
	from D:/a/metanorma-standoc/metanorma-standoc/lib/metanorma/standoc/utils.rb:13:in `convert'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/asciidoctor-2.0.20/lib/asciidoctor/abstract_block.rb:76:in `convert'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/asciidoctor-2.0.20/lib/asciidoctor/abstract_block.rb:85:in `block in content'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/asciidoctor-2.0.20/lib/asciidoctor/abstract_block.rb:85:in `map'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/asciidoctor-2.0.20/lib/asciidoctor/abstract_block.rb:85:in `content'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/asciidoctor-2.0.20/lib/asciidoctor/document.rb:1012:in `content'
	from D:/a/metanorma-standoc/metanorma-standoc/lib/metanorma/standoc/base.rb:231:in `block in middle'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/builder.rb:433:in `insert'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/builder.rb:415:in `method_missing'
	from D:/a/metanorma-standoc/metanorma-standoc/lib/metanorma/standoc/base.rb:230:in `middle'
	from D:/a/metanorma-standoc/metanorma-standoc/lib/metanorma/standoc/base.rb:200:in `block in makexml1'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/builder.rb:331:in `initialize'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/builder.rb:295:in `new'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/builder.rb:295:in `with'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/metanorma-utils-1.7.0/lib/utils/xml.rb:54:in `noko'
	from D:/a/metanorma-standoc/metanorma-standoc/lib/metanorma/standoc/utils.rb:21:in `noko'
	from D:/a/metanorma-standoc/metanorma-standoc/lib/metanorma/standoc/base.rb:200:in `makexml1'
	from D:/a/metanorma-standoc/metanorma-standoc/lib/metanorma/standoc/base.rb:206:in `makexml'
	from D:/a/metanorma-standoc/metanorma-standoc/lib/metanorma/standoc/base.rb:152:in `document1'
	from D:/a/metanorma-standoc/metanorma-standoc/lib/metanorma/standoc/base.rb:141:in `document'
	from D:/a/metanorma-standoc/metanorma-standoc/lib/metanorma/standoc/utils.rb:13:in `convert'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/asciidoctor-2.0.20/lib/asciidoctor/document.rb:956:in `convert'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/asciidoctor-2.0.20/lib/asciidoctor/convert.rb:120:in `convert'
	from D:/a/metanorma-standoc/metanorma-standoc/spec/metanorma/refs_fetch_spec.rb:1015:in `block (3 levels) in <top (required)>'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/vcr-6.1.0/lib/vcr/util/variable_args_block_caller.rb:9:in `call_block'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/vcr-6.1.0/lib/vcr.rb:194:in `use_cassette'
	from D:/a/metanorma-standoc/metanorma-standoc/spec/metanorma/refs_fetch_spec.rb:956:in `block (2 levels) in <top (required)>'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:263:in `instance_exec'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:263:in `block in run'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:511:in `block in with_around_and_singleton_context_hooks'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:468:in `block in with_around_example_hooks'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:486:in `block in run'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:626:in `block in run_around_example_hooks_for'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:352:in `call'
	from D:/a/metanorma-standoc/metanorma-standoc/spec/spec_helper.rb:40:in `block (2 levels) in <top (required)>'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:390:in `execute_with'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:352:in `call'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:629:in `run_around_example_hooks_for'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:486:in `run'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:468:in `with_around_example_hooks'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:511:in `with_around_and_singleton_context_hooks'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:259:in `run'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:646:in `block in run_examples'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:642:in `map'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:642:in `run_examples'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:607:in `run'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:121:in `map'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/configuration.rb:2070:in `with_suite_hooks'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:116:in `block in run_specs'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/reporter.rb:74:in `report'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:115:in `run_specs'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:89:in `run'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:71:in `run'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:45:in `invoke'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/exe/rspec:4:in `<main>'
  ```
</details>

Full log: https://github.com/metanorma/metanorma-standoc/actions/runs/7458621234/job/20294257836#step:6:64

Possible inspiration to fix: https://github.com/metanorma/metanorma/pull/307

**Comment by CAMOBAP** [comment]
@alexeymorozov you did a great job troubleshooting such kind of issue in metanorma before, maybe you have a chance to have a look at those ones

**Comment by alexeymorozov** [comment]
I'll see what's happening 👍
