### ISSUE TITLE
Metanorma attachments not working (absolute path, failiure in encoding)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#898]
From:
* https://github.com/metanorma/annotated-express-report/issues/15

To reproduce:
* Checkout the branch `pdf-latex-validation-report-attachments`
* Run: `bundle exec metanorma sources/report-pdf-latex-validation/document.adoc`

There are two issues:

1. The attachments code expects the declared attachments path to start from PWD, instead of the document root (`sources/report-pdf-latex-validation`), or the local file root (`sources/report-pdf-latex-validation/10303-49/`)
2. The attachment process fails:

```
<internal:pack>:29:in `unpack1'
ruby/3.3.0/base64.rb:298:in `strict_decode64'
ruby/gems/3.3.0/gems/isodoc-2.10.6/lib/isodoc/presentation_function/metadata.rb:27:in `block in save_attachment'
ruby/gems/3.3.0/gems/isodoc-2.10.6/lib/isodoc/presentation_function/metadata.rb:27:in `open'
ruby/gems/3.3.0/gems/isodoc-2.10.6/lib/isodoc/presentation_function/metadata.rb:27:in `save_attachment'
ruby/gems/3.3.0/gems/isodoc-2.10.6/lib/isodoc/presentation_function/metadata.rb:20:in `block in attachments_extract'
ruby/gems/3.3.0/gems/nokogiri-1.16.6-arm64-darwin/lib/nokogiri/xml/node_set.rb:235:in `block in each'
ruby/gems/3.3.0/gems/nokogiri-1.16.6-arm64-darwin/lib/nokogiri/xml/node_set.rb:234:in `upto'
ruby/gems/3.3.0/gems/nokogiri-1.16.6-arm64-darwin/lib/nokogiri/xml/node_set.rb:234:in `each'
ruby/gems/3.3.0/gems/isodoc-2.10.6/lib/isodoc/presentation_function/metadata.rb:19:in `attachments_extract'
ruby/gems/3.3.0/gems/isodoc-2.10.6/lib/isodoc/presentation_function/metadata.rb:6:in `metadata'
ruby/gems/3.3.0/gems/isodoc-2.10.6/lib/isodoc/presentation_xml_convert.rb:42:in `conversions'
ruby/gems/3.3.0/gems/isodoc-2.10.6/lib/isodoc/presentation_xml_convert.rb:28:in `convert1'
ruby/gems/3.3.0/gems/metanorma-iso-2.8.1/lib/isodoc/iso/presentation_xml_convert.rb:23:in `convert1'
ruby/gems/3.3.0/gems/isodoc-2.10.6/lib/isodoc/convert.rb:168:in `convert'
ruby/gems/3.3.0/gems/metanorma-iso-2.8.1/lib/metanorma/iso/processor.rb:69:in `output'
ruby/gems/3.3.0/gems/metanorma-2.0.3/lib/metanorma/compile/compile.rb:184:in `process_output_unthreaded'
ruby/gems/3.3.0/gems/metanorma-2.0.3/lib/metanorma/compile/compile.rb:170:in `process_exts1'
ruby/gems/3.3.0/gems/metanorma-2.0.3/lib/metanorma/compile/compile.rb:143:in `process_ext'
ruby/gems/3.3.0/gems/metanorma-2.0.3/lib/metanorma/compile/compile.rb:125:in `block in process_exts_run'
ruby/gems/3.3.0/gems/metanorma-2.0.3/lib/metanorma/compile/compile.rb:124:in `each'
ruby/gems/3.3.0/gems/metanorma-2.0.3/lib/metanorma/compile/compile.rb:124:in `process_exts_run'
ruby/gems/3.3.0/gems/metanorma-2.0.3/lib/metanorma/compile/compile.rb:119:in `process_exts'
```

**Comment by opoudjis** [comment]
> The attachments code expects the declared attachments path to start from PWD, instead of the document root (`sources/report-pdf-latex-validation`), or the local file root (`sources/report-pdf-latex-validation/10303-49/`)

Images are postprocessed to be relative to the document root.  Doing the same for attachments.

**Comment by opoudjis** [comment]
I'm seeing that the absolute links are happening after  all, if the document is compiled in a document outside the PWD. Ugh. Fighting against Asciidoctor is a recurring waste of resources. Will convert the link to a relative link.
