### ISSUE TITLE
Fatal Error: uninitialized constant Metanorma::Standoc::Validate::Iev

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-standoc#951]
https://github.com/metanorma/metanorma-docker/actions/runs/12484331667/job/34854236948#step:7:18

```
Fatal Error: uninitialized constant Metanorma::Standoc::Validate::Iev

        @iev = Iev::Db.new(@iev_globalname, @iev_localname) unless @no_isobib
               ^^^
Did you mean?  IEV
/usr/local/bundle/gems/metanorma-standoc-2.10.4/lib/metanorma/standoc/validate_term.rb:10:in `init_iev': uninitialized constant Metanorma::Standoc::Validate::Iev (NameError)

        @iev = Iev::Db.new(@iev_globalname, @iev_localname) unless @no_isobib
               ^^^
Did you mean?  IEV
	from /usr/local/bundle/gems/metanorma-standoc-2.10.4/lib/metanorma/standoc/validate_term.rb:15:in `iev_validate'
	from /usr/local/bundle/gems/metanorma-standoc-2.10.4/lib/metanorma/standoc/validate.rb:20:in `content_validate'
	from /usr/local/bundle/gems/metanorma-iso-2.9.3/lib/metanorma/iso/validate.rb:162:in `content_validate'
	from /usr/local/bundle/gems/metanorma-iso-2.9.3/lib/metanorma/iso/validate.rb:[19](https://github.com/metanorma/metanorma-docker/actions/runs/12484331667/job/34854236948#step:7:20)7:in `validate'
	from /usr/local/bundle/gems/metanorma-standoc-2.10.4/lib/metanorma/standoc/base.rb:101:in `makexml'
	from /usr/local/bundle/gems/metanorma-standoc-2.10.4/lib/metanorma/standoc/base.rb:43:in `document1'
	from /usr/local/bundle/gems/metanorma-standoc-2.10.4/lib/metanorma/standoc/base.rb:32:in `document'
	from /usr/local/bundle/gems/metanorma-standoc-2.10.4/lib/metanorma/standoc/utils.rb:13:in `convert'
	from /usr/local/bundle/gems/asciidoctor-2.0.23/lib/asciidoctor/document.rb:956:in `convert'
	from /usr/local/bundle/gems/asciidoctor-2.0.23/lib/asciidoctor/convert.rb:1[20](https://github.com/metanorma/metanorma-docker/actions/runs/12484331667/job/34854236948#step:7:21):in `convert'
	from /usr/local/bundle/gems/metanorma-2.0.10/lib/metanorma/input/asciidoc.rb:13:in `process'
	from /usr/local/bundle/gems/metanorma-2.0.10/lib/metanorma/processor/processor.rb:[21](https://github.com/metanorma/metanorma-docker/actions/runs/12484331667/job/34854236948#step:7:22):in `input_to_isodoc'
	from /usr/local/bundle/gems/metanorma-2.0.10/lib/metanorma/compile/compile.rb:73:in `process_input_adoc'
	from /usr/local/bundle/gems/metanorma-2.0.10/lib/metanorma/compile/compile.rb:55:in `process_input'
	from /usr/local/bundle/gems/metanorma-2.0.10/lib/metanorma/compile/compile.rb:31:in `compile'
	from /usr/local/bundle/gems/metanorma-cli-1.11.3/lib/metanorma/cli/compiler.rb:45:in `compile_file'
	from /usr/local/bundle/gems/metanorma-cli-1.11.3/lib/metanorma/cli/compiler.rb:30:in `compile'
	from /usr/local/bundle/gems/metanorma-cli-1.11.3/lib/metanorma/cli/compiler.rb:35:in `compile'
	from /usr/local/bundle/gems/metanorma-cli-1.11.3/lib/metanorma/cli/site_generator.rb:97:in `compile'
	from /usr/local/bundle/gems/metanorma-cli-1.11.3/lib/metanorma/cli/site_generator.rb:32:in `block in generate'
	from /usr/local/bundle/gems/metanorma-cli-1.11.3/lib/metanorma/cli/site_generator.rb:32:in `map'
	from /usr/local/bundle/gems/metanorma-cli-1.11.3/lib/metanorma/cli/site_generator.rb:32:in `generate'
	from /usr/local/bundle/gems/metanorma-cli-1.11.3/lib/metanorma/cli/site_generator.rb:26:in `generate'
	from /usr/local/bundle/gems/metanorma-cli-1.11.3/lib/metanorma/cli/commands/site.rb:33:in `generate'
	from /usr/local/bundle/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'
	from /usr/local/bundle/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
	from /usr/local/bundle/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.3.2/lib/thor.rb:538:in `dispatch'
	from /usr/local/bundle/gems/thor-1.3.2/lib/thor/invocation.rb:116:in `invoke'
	from /usr/local/bundle/gems/thor-1.3.2/lib/thor.rb:338:in `block in subcommand'
	from /usr/local/bundle/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'
	from /usr/local/bundle/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
	from /usr/local/bundle/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.3.2/lib/thor.rb:538:in `dispatch'
	from /usr/local/bundle/gems/thor-1.3.2/lib/thor/base.rb:584:in `start'
	from /usr/local/bundle/gems/metanorma-cli-1.11.3/lib/metanorma/cli.rb:34:in `start'
	from /usr/local/bundle/gems/metanorma-cli-1.11.3/exe/metanorma:[25](https://github.com/metanorma/metanorma-docker/actions/runs/12484331667/job/34854236948#step:7:26):in `block in <top (required)>'
	from /usr/local/bundle/gems/metanorma-cli-1.11.3/exe/metanorma:43:in `<top (required)>'
	from /usr/local/bundle/bin/metanorma:25:in `load'
	from /usr/local/bundle/bin/metanorma:25:in `<main>'
```

**Comment by opoudjis** [comment]
Already addressed in https://github.com/metanorma/metanorma-standoc/pull/950/. I updated IEV, and that seems to have reverted the gem class name...
